version: '3'
services:
  backend:
    image: cookierocket/doodling-back
    environment:
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_HOST: ${RDS_HOST}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_DATABASE: ${RDS_DATABASE}
      RDS_PORT: ${RDS_PORT}
    container_name: "doodling-back"
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3065:3065"