version: '3'
services:
  backend:
    image: kapable/doodling-back
    environment:
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_HOST: ${RDS_HOST}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_DATABASE: ${RDS_DATABASE}
      RDS_PORT: ${RDS_PORT}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      COOKIE_SECRET: ${COOKIE_SECRET}
      SERVICE_FRONT_URL: ${SERVICE_FRONT_URL}
      SERVICE_FRONT_URL2: ${SERVICE_FRONT_URL2}
      API_DOCS_URL: ${API_DOCS_URL}
    container_name: "doodling-back"
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3065:3065"