version: '3'
services:
  backend:
    image: cookierocket/doodling-back-dev
    environment:
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_HOST: ${RDS_HOST}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_DATABASE: ${RDS_DATABASE}
      RDS_PORT: ${RDS_PORT}
    container_name: "doodling-back-dev"
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3065:3065"
    volumes:
      # hot reload를 위해 mount
      - "/app/node_modules"
      - "./:/usr/src/app"